/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData icon_phone = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icon_search = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icon_heart_solid = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData icon_heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData icon_check = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_picture = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icon_camera_solid = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_calendar = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icon_bookmark_solid = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_share = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icon_delete = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData icon_location_solid = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData icon_like = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData icon_bell = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData icon_info_solid = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData icon_plus = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData icon_edit = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_users = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_user = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_link = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData icon_store = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData icon_checked = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData icon_check_circle = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData icon_plus_circle = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData icon_uncheck = const IconData(0xf096, fontFamily: _kFontFam);
  static const IconData icon_bookmark = const IconData(0xf097, fontFamily: _kFontFam);
  static const IconData icon_filter_solid = const IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData icon_money_cash = const IconData(0xf0d6, fontFamily: _kFontFam);
  static const IconData icon_direction = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData icon_schedule = const IconData(0xf133, fontFamily: _kFontFam);
  static const IconData icon_more_horiz = const IconData(0xf141, fontFamily: _kFontFam);
  static const IconData icon_more_vert = const IconData(0xf142, fontFamily: _kFontFam);
  static const IconData icon_like_solid = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData icon_female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData icon_male = const IconData(0xf183, fontFamily: _kFontFam);
  static const IconData icon_bug = const IconData(0xf188, fontFamily: _kFontFam);
  static const IconData icon_plus_square = const IconData(0xf196, fontFamily: _kFontFam);
  static const IconData icon_phone_app = const IconData(0xf232, fontFamily: _kFontFam);
}
