name: phieucaphe
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^1.9.1+hotfix.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
#  flutter_staggered_grid_view: "^0.2.7"
#  cached_network_image: ^2.0.0-rc.1

  carousel_slider: ^1.3.1
  uuid: ^2.0.2
  equatable: ^0.6.1
  path_drawing: ^0.4.1
  oktoast: ^2.2.0
  mobx: ^0.3.9+1
  kiwi: ^0.2.0
  provider: ^3.1.0+1
  video_player: ^0.10.4+1
  video_player_web:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/video_player/video_player_web
  html: ^0.14.0+3
  flutter_html: ^0.11.0
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          style: normal
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 200